pod 'AFNetworking', '~> 2.0'
pod 'DateTools'
pod 'SVProgressHUD'
pod 'HockeySDK', '~> 3.7.2'
pod 'HTKDynamicResizingCell'
pod 'PureLayout'
pod 'DTMHeatmap'
pod 'LPPopupListView'
pod 'CCHMapClusterController'
pod 'Parse', '~> 1.8.5'
pod 'ParseFacebookUtilsV4', '~> 1.8.5'
pod 'ParseUI'
pod 'FBSDKShareKit'
pod 'DeepLinkKit'